name = "leadgress-landing"
compatibility_date = "2024-11-21"

# Cloudflare Pages Functions
pages_build_output_dir = "dist"

[[d1_databases]]
# Update database_id after running: wrangler d1 create leads-db
binding = "LEADS_DB"
database_name = "leads-db"
database_id = "7289ddb3-5c5e-421c-9859-34cd57857925"


